config/routes.rb
Rails.application.routes.draw do
  resources :restaurants

  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

end

app/models/restaurant.rb
class Restaurant
  include ActiveModel::Model
  attr_accessor :address, :city, :state, :radius, :term
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include Yelp::V1::Review::Request
  include Yelp::V2::Business::Request

  def index

  end

  def show
    client = Yelp::Client.new
    request = Id.new(
    :yelp_business_id => params[:id])
    @response = client.search(request)
  end

  def new
     @restaurant_search = Restaurant.new
  end

  def create
    client = Yelp::Client.new
    request = Location.new(
             :address => params["restaurant"][:address],
             :city => params["restaurant"][:city],
             :state => params["restaurant"][:state],
             :radius =>params["restaurant"][:radius],
             :term => params["restaurant"][:term])
    @restaurants = client.search(request)
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body class="container">
  <header class="page-header">
      <ul class = "nav nav-pills">
        <li class="active"><a href="/restaurants/new">Food Finder</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
  </header>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="center-block jumbotron">
  <div class="container">
  <p>This is a site that searches for food, using the Yelp API! More to come.</p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="center-block jumbotron">
  <div class="container">

    <p>Site by Caleb and Alla.</p>
    <p>Come find us on Github at:</p>
    <p><a href= "https://github.com/calebthill"> https://github.com/calebthill </a>
    <a href= "https://github.com/RSid">https://github.com/RSid</a></p>
  </div>
</div>

app/views/restaurants/index.html.erb
<h1> Results </h1>

<ul>
  <% @restaurants["businesses"].each do |business| %>
  <li>
    <%= link_to business["name"], restaurant_path(business["id"]) %>
  </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2> What's for Dinner? </h2>
  </div>
</div>

<div class="center-block jumbotron">
  <div class="container">
  <%= form_for @restaurant_search do |f| %>
    <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %> <br>

    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %> <br>

    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %> <br>

    <%= f.label :miles_away %>
    <%= f.text_field :radius, class: "form-control" %> <br>

    <%= f.label :food_type  %>
    <%= f.text_field :term, class: "form-control" %> <br><br>

    <div><%= f.submit "Search Restaurants", class: "btn btn-default" %></div>
  <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="center-block jumbotron" center>
  <div class="container">
    <h2><%= @response["name"] %></h2>
    <br>
    <h4>Phone:</h4>
    <p><%= @response["phone"] %></p>
    <br>
    <h4>Address:</h4>
    <p><%= @response["location"]["address"][0] %> <%= @response["location"]["city"] %>
       <%= @response["location"]["state_code"] %> <%= @response["location"]["postal_code"] %></p>
    <br>
    <h4>Rating:</h4>
    <p> <%= @response["rating"] %></p>
  </div>
</div>